version: '3'
services:
  pwrstat:
    build: ./
    environment:
      - HTTP_HOST=0.0.0.0
    ports:
      - 3000:3000  # for curl demo only
    devices:
      - /dev/usb/hiddev0

  influxdb:
    image: influxdb:2.0-alpine
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=demo
      - DOCKER_INFLUXDB_INIT_PASSWORD=demo-insecure
      - DOCKER_INFLUXDB_INIT_ORG=demo-org
      - DOCKER_INFLUXDB_INIT_BUCKET=demo-bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=demo-insecure-admin-token

  telegraf:
    image: telegraf:1.19-alpine
    volumes:
      - ./data/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    environment:
      - INFLUX_ORG=demo-org
      - INFLUX_BUCKET=demo-bucket
      - INFLUX_TOKEN=demo-insecure-admin-token

  grafana:
    image: grafana/grafana
    ports:
      - 3001:3000
    volumes:
      - ./data/grafana/dashboards:/var/lib/grafana/dashboards
      - ./data/grafana/provisioning:/etc/grafana/provisioning
